#!/usr/bin/env python2.5
from pydoctor.driver import main
import sys

args = []
args.append("--add-package=pyEDA/FVMEqn")
args.append("--add-package=pyEDA/Mesh")
args.append("--add-package=pyEDA/PDE")
args.append("--add-package=pyEDA/Circuit")

args.append("--make-html")
args.append("--project-name=pyEDA")

sys.exit(main(args))

